# Jekyll configuration
title: Snakemake day 2017
description: Amsterdam, The Netherlands, December 15, 2017
show_downloads: false
theme: cayman
url: "https://snakemake-days.github.io/"
gems:
- jekyll-mentions
